#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
echo WELCOME TO $( hostname | tr a-z A-Z ), $( whoami | tr a-z A-Z )
echo DATE: $( date | tr a-z A-Z )
echo 
if (( $+commands[fortune] )); then
  echo FORTUNE:
  fortune
  echo 
fi
