#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="/usr/local/share/python/:/Applications/Utilities/Postgres.app/Contents/MacOS/bin:/usr/local/bin:/usr/local/Cellar/ruby/2.0.0-p195/bin:/opt/local/bin:/opt/local/sbin:$PATH"
export EDITOR=vim

alias ls='ls -G'
alias lsl='ls -Gl'
alias lsa='ls -Ga'
alias lsal='ls -Gla'
function cds () {
    cd $1
    ls
}

alias umssh='ssh cbothner@login.itcs.umich.edu'
alias remley='ssh ladmin@remley.wcbn.org'
alias sleepytime='python ~/Documents/Personal/Code/sleepytime.py'
alias wifi='networksetup -setairportpower en1'
alias x='exit'
alias c='clear'
alias mutt='cd ~/Desktop && mutt'
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Directory aliases are not common across machines, so source the local file
if [[ -s "${ZDOTDIR:~$HOME}/.zshdirs" ]]; then
  source "${ZDOTDIR:~$HOME}/.zshdirs"
fi
