" Smashing escape mapping
inoremap jk <Esc>
inoremap kj <Esc>

" Setting line numbers
set number

call plug#begin('~/.config/vim/plugged')

Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

call plug#end()

" Shortcuts for FZF commands
nnoremap <C-p> :GFiles<CR>
nnoremap <C-t> :Buffers<CR>
nnoremap <C-f> :Rg<CR>
