#
# Executes commands at login post-zshrc.
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

echo Welcome to $( hostname ), $( whoami )
echo Today’s date is $( date )

if [[ -f ~/setup-in-progress ]]; then
  echo
  echo "⚠️   Environment setup is ongoing. This shell does not have the full environment configured."
fi
