#
# Executes commands at the start of an interactive session.
#

alias vim='nvim'

# Installing FZF
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
sudo rm -rf /usr/local/bin/fzf
sudo rm -rf /usr/bin/fzf

export PS1="%d \$ "
